//
// SimpleDate.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.SimpleDate

import Vapor

public typealias SimpleDate = Date
