//
// SimpleString.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.SimpleString

import Vapor

/** Simple String */
public typealias SimpleString = String
