import Vapor
// AuthenticationApiDelegate.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /APIs.Authentication


public enum anotherSecurityProtectedEndpointResponse: ResponseEncodable {
  case http200(SecurityProtectedEndpointResponse)

  public func encodeResponse(for request: Request) -> EventLoopFuture<Response> {
    switch self {
    case .http200(let content):
      return content.encodeResponse(for: request).map { (response: Response) -> (Response) in
        response.status = HTTPStatus(statusCode: 200)
        return response
      }
    }
  }
}


public enum securityProtectedEndpointResponse: ResponseEncodable {
  case http200(SecurityProtectedEndpointResponse)

  public func encodeResponse(for request: Request) -> EventLoopFuture<Response> {
    switch self {
    case .http200(let content):
      return content.encodeResponse(for: request).map { (response: Response) -> (Response) in
        response.status = HTTPStatus(statusCode: 200)
        return response
      }
    }
  }
}

public protocol AuthenticationApiDelegate {
  associatedtype AuthType
  /**
  GET /authentication/another */
  func anotherSecurityProtectedEndpoint(with req: Request, asAuthenticated user: AuthType) throws -> EventLoopFuture<anotherSecurityProtectedEndpointResponse>
  /**
  GET /authentication/single */
  func securityProtectedEndpoint(with req: Request, asAuthenticated user: AuthType) throws -> EventLoopFuture<securityProtectedEndpointResponse>
}
