//
// MultipleResponseCodeRequest.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.MultipleResponseCodeRequest

import Vapor


public final class MultipleResponseCodeRequest: Content {

    public enum ResponseCode: String, Content { 
        case _200 = "200"
        case _201 = "201"
        case _401 = "401"
        case _500 = "500"
    }

    public var responseCode: ResponseCode

    public init(responseCode: ResponseCode) { 
        self.responseCode = responseCode
    }

}
