//
// MultipleParameterResponse.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.MultipleParameterResponse

import Vapor


public final class MultipleParameterResponse: Content {

    public var param1: String
    public var param2: String

    public init(param1: String, param2: String) { 
        self.param1 = param1
        self.param2 = param2
    }

}
