//
// QueryParametersResponse.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.QueryParametersResponse

import Vapor


public final class QueryParametersResponse: Content {

    public var param1: String
    public var param2: Int?

    public init(param1: String, param2: Int?) { 
        self.param1 = param1
        self.param2 = param2
    }

}
