//
// SecurityProtectedEndpointResponse.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SecurityProtectedEndpointResponse

import Vapor


public final class SecurityProtectedEndpointResponse: Content {

    public enum SecuredBy: String, Content { 
        case security1 = "Security1"
        case security2 = "Security2"
    }

    public var secret: String
    public var securedBy: SecuredBy

    public init(secret: String, securedBy: SecuredBy) { 
        self.secret = secret
        self.securedBy = securedBy
    }

}
