//
// SimpleBoolean.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SimpleBoolean

import Vapor

public typealias SimpleBoolean = Bool
