//
// SimpleString.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SimpleString

import Vapor

/** Simple String */
public typealias SimpleString = String
