//
// SimpleEnumString.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.SimpleEnumString

import Vapor

/** Enumerated string object */
public enum SimpleEnumString: String, Codable {
    case _1 = "Value 1"
    case _2 = "Value 2"
}