//
// RequestHeadersResponse.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.RequestHeadersResponse

import Vapor


public final class RequestHeadersResponse: Content {

    /** Returns the required header that was sent */
    public var requiredHeader: String
    /** Returns the array header that was sent */
    public var arrayHeader: [String]?

    public init(requiredHeader: String, arrayHeader: [String]?) { 
        self.requiredHeader = requiredHeader
        self.arrayHeader = arrayHeader
    }

}
