//
// SimpleBoolean.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.SimpleBoolean

import Vapor

public typealias SimpleBoolean = Bool
