//
// SimpleNumber.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.SimpleNumber

import Vapor

/** Simple Number */
public typealias SimpleNumber = Decimal
