//
// SimpleDate.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SimpleDate

import Vapor

public typealias SimpleDate = Date
