//
// SimpleInteger.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SimpleInteger

import Vapor

/** Simple Integer */
public typealias SimpleInteger = Int
