//
// SimpleInteger.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.SimpleInteger

import Vapor

/** Simple Integer */
public typealias SimpleInteger = Int
