//
// SimpleEnumString.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SimpleEnumString

import Vapor

/** Enumerated string object */
public enum SimpleEnumString: String, Codable {
    case _1 = "Value 1"
    case _2 = "Value 2"
}