//
// SimpleNumber.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SimpleNumber

import Vapor

/** Simple Number */
public typealias SimpleNumber = Decimal
