//
// SimpleObject.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /Models.SimpleObject

import Vapor


public final class SimpleObject: Content {

    public var simpleString: SimpleString
    public var simpleNumber: SimpleNumber
    public var simpleInteger: SimpleInteger
    public var simpleDate: SimpleDate
    public var simpleEnumString: SimpleEnumString
    public var simpleBoolean: SimpleBoolean
    public var simpleArray: [SimpleString]

    public init(simpleString: SimpleString, simpleNumber: SimpleNumber, simpleInteger: SimpleInteger, simpleDate: SimpleDate, simpleEnumString: SimpleEnumString, simpleBoolean: SimpleBoolean, simpleArray: [SimpleString]) { 
        self.simpleString = simpleString
        self.simpleNumber = simpleNumber
        self.simpleInteger = simpleInteger
        self.simpleDate = simpleDate
        self.simpleEnumString = simpleEnumString
        self.simpleBoolean = simpleBoolean
        self.simpleArray = simpleArray
    }

}
