import Vapor
// AuthenticationApiDelegate.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /APIs.Authentication


public enum securityProtectedEndpointResponse: ResponseEncodable {
  case http200

  public func encode(for request: Request) throws -> EventLoopFuture<Response> {
    let response = request.response()
    switch self {
    case .http200:
      response.http.status = HTTPStatus(statusCode: 200)
    }
    return Future.map(on: request) { response }
  }
}

public protocol AuthenticationApiDelegate {
  /**
	GET /authentication/single */
    
    func securityProtectedEndpoint(with req: Request) throws -> Future<securityProtectedEndpointResponse>
}
