import Vapor
// DataModelApiDelegate.swift
//
// Generated by SwiftVapor3 swagger-codegen
// https://github.com/swagger-api/swagger-codegen
// Template Input: /APIs.DataModel


public enum referencedObjectResponse: ResponseEncodable {
  case http200(SimpleObject)

  public func encode(for request: Request) throws -> EventLoopFuture<Response> {
    let response = request.response()
    switch self {
    case .http200(let content):
      response.http.status = HTTPStatus(statusCode: 200)
      try response.content.encode(content)
    }
    return Future.map(on: request) { response }
  }
}

public protocol DataModelApiDelegate {
  /**
	POST /schema/referenced/object
    Test data model support */
    
    func referencedObject(with req: Request, body: SimpleObject) throws -> Future<referencedObjectResponse>
}
