import Vapor
// DataModelApiDelegate.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /APIs.DataModel


public enum referencedObjectResponse: ResponseEncodable {
  case http200(SimpleObject)

  public func encodeResponse(for request: Request) -> EventLoopFuture<Response> {
    switch self {
    case .http200(let content):        return content.encodeResponse(for: request).map { (response: Response) -> (Response) in
        response.status = HTTPStatus(statusCode: 200)
        return response
      }
    }
  }
}

public protocol DataModelApiDelegate {
  associatedtype AuthType
  /**
  POST /schema/referenced/object
  Test data model support */
  func referencedObject(with req: Request, body: SimpleObject) throws -> EventLoopFuture<referencedObjectResponse>
}
