#!/bin/sh

cd ../../../../../
docker-compose -f src/test/resources/WithoutAuthTest/VaporTestServer/docker-compose.yml build
docker-compose -f src/test/resources/WithoutAuthTest/VaporTestServer/docker-compose.yml up --abort-on-container-exit
docker-compose -f src/test/resources/WithoutAuthTest/VaporTestServer/docker-compose.yml down
