#!/bin/sh

cd ../../../../../
docker-compose -f src/test/resources/AllTest/VaporTestServer/docker-compose.yml build
docker-compose -f src/test/resources/AllTest/VaporTestServer/docker-compose.yml up --abort-on-container-exit
